### ISSUE TITLE
IOMMU not loaded Skylake i5

### ISSUE THREAD

**Issue by TheGreatestJannet** [ipaqmaster/vfio#2]
Hi I have an i5 6500 and a Asus z170i pro gaming motherboard. I have enabled Intel VT-D in the bios. My bootloader is Systemd-boot and I'm using: `options root="LABEL=arch_os" rw snd_hda_intel.power_save=0 nvidia-drm.modeset=1 nouveau.modeset=0 intel_iommu=on`. For the script I'm running: `./main -image /var/lib/libvirt/images/Win10-Gaming.img,format=qcow2 -pci '|NVIDIA|8086:a170|8086:a12f|1b21:1242'`. However when running the script I get: 
```
This is a DRY run. Please specify -run to actually run
IOMMU isn't loaded?
  For an Intel machine you must add 'intel_iommu=on' to your kernel boot options in your bootloader.
  If you're on an AMD machine instead add these two: 'iommu=pt iommu=1'

  If you've already done this and rebooted, your host may not be compatible or some relevant bios settings could be disabled.
  Feel free to ask about this in case it's a script fault.
```
I have passthrough my USB controller before so I believe my CPU and Motherboard supports IOMMU. Do you have any idea why this error is showing?

**Comment by ipaqmaster** [comment]
Hey sorry to hear the script's giving you trouble. On line 318 it does a check for IOMMU by greping for a mention of it in lsmod (such as the module: vfio_**iommu**_type1) . But as you've done passthrough on your setup already then chances are this check has failed.

Can you try running the below on your affected machine and let me know what line it spits out? I might use this check method instead if it works.
  `if [ -z "$(find /sys/class/iommu/ -type l)" ]; then echo "empty set, no iommu?"; else echo "Found it" ; fi`

**Comment by TheGreatestJannet** [comment]
It returned, Found it.

**Comment by ipaqmaster** [comment]
Nice, I'll add that now and you should be able to pull the update.

**Comment by ipaqmaster** [comment]
Ok pull the latest. Hopefully it'll help (commit aeb7f701f1bfef24fab143d64e5a70b6189cbf7b)

**Comment by TheGreatestJannet** [comment]
Thank you! It is now working but it wants to bind all my PCI Devices for some reason:
```
sudo ./main -image /var/lib/libvirt/images/Win10-Gaming.img,format=qcow2 -pci '|NVIDIA|8086:a170|8086:a12f|1b21:1242'                                                                                
This is a DRY run. Please specify -run to actually run
-taskset not specified, using all host cores: (4) with (4) threads.
-memory argument not provided, will use half of host: 8199624K
-bios argument not provided, using discovered default: /usr/share/ovmf/x64/OVMF_CODE.fd

PCI:
  Matched: 00:00.0 Host bridge [0600]: Intel Corporation Xeon E3-1200 v5/E3-1500 v5/6th Gen Core Processor Host Bridge/DRAM Registers [8086:191f] (rev 07)
   [INFO] Driver is 'skl_uncore' and will be rebound on VM exit
    [DRY] Not unbinding it
    [DRY] Not binding to vfio-pci

  Matched: 00:01.0 PCI bridge [0604]: Intel Corporation Xeon E3-1200 v5/E3-1500 v5/6th Gen Core Processor PCIe Controller (x16) [8086:1901] (rev 07)
   [INFO] Driver is 'pcieport' and will be rebound on VM exit
    [DRY] Not unbinding it
    [DRY] Not binding to vfio-pci

  Matched: 00:14.0 USB controller [0c03]: Intel Corporation 100 Series/C230 Series Chipset Family USB 3.0 xHCI Controller [8086:a12f] (rev 31)
   [INFO] Driver is 'xhci_hcd' and will be rebound on VM exit
    [DRY] Not unbinding it
    [DRY] Not binding to vfio-pci

  Matched: 00:16.0 Communication controller [0780]: Intel Corporation 100 Series/C230 Series Chipset Family MEI Controller #1 [8086:a13a] (rev 31)
   [INFO] Driver is 'mei_me' and will be rebound on VM exit
    [DRY] Not unbinding it
    [DRY] Not binding to vfio-pci

  Matched: 00:17.0 SATA controller [0106]: Intel Corporation Q170/Q150/B150/H170/H110/Z170/CM236 Chipset SATA Controller [AHCI Mode] [8086:a102] (rev 31)
   [INFO] Driver is 'ahci' and will be rebound on VM exit
    [DRY] Not unbinding it
    [DRY] Not binding to vfio-pci

  Matched: 00:1b.0 PCI bridge [0604]: Intel Corporation 100 Series/C230 Series Chipset Family PCI Express Root Port #17 [8086:a167] (rev f1)
   [INFO] Driver is 'pcieport' and will be rebound on VM exit
    [DRY] Not unbinding it
    [DRY] Not binding to vfio-pci

  Matched: 00:1c.0 PCI bridge [0604]: Intel Corporation 100 Series/C230 Series Chipset Family PCI Express Root Port #1 [8086:a110] (rev f1)
   [INFO] Driver is 'pcieport' and will be rebound on VM exit
    [DRY] Not unbinding it
    [DRY] Not binding to vfio-pci

  Matched: 00:1d.0 PCI bridge [0604]: Intel Corporation 100 Series/C230 Series Chipset Family PCI Express Root Port #9 [8086:a118] (rev f1)
   [INFO] Driver is 'pcieport' and will be rebound on VM exit
    [DRY] Not unbinding it
    [DRY] Not binding to vfio-pci

  Matched: 00:1d.1 PCI bridge [0604]: Intel Corporation 100 Series/C230 Series Chipset Family PCI Express Root Port #10 [8086:a119] (rev f1)
   [INFO] Driver is 'pcieport' and will be rebound on VM exit
    [DRY] Not unbinding it
    [DRY] Not binding to vfio-pci

  Matched: 00:1d.2 PCI bridge [0604]: Intel Corporation 100 Series/C230 Series Chipset Family PCI Express Root Port #11 [8086:a11a] (rev f1)
   [INFO] Driver is 'pcieport' and will be rebound on VM exit
    [DRY] Not unbinding it
    [DRY] Not binding to vfio-pci

  Matched: 00:1f.0 ISA bridge [0601]: Intel Corporation Z170 Chipset LPC/eSPI Controller [8086:a145] (rev 31)
    [DRY] Not unbinding it
    [DRY] Not binding to vfio-pci

  Matched: 00:1f.2 Memory controller [0580]: Intel Corporation 100 Series/C230 Series Chipset Family Power Management Controller [8086:a121] (rev 31)
    [DRY] Not unbinding it
    [DRY] Not binding to vfio-pci

  Matched: 00:1f.3 Audio device [0403]: Intel Corporation 100 Series/C230 Series Chipset Family HD Audio Controller [8086:a170] (rev 31)
   [INFO] Driver is 'snd_hda_intel' and will be rebound on VM exit
    [DRY] Not unbinding it
    [DRY] Not binding to vfio-pci

  Matched: 00:1f.4 SMBus [0c05]: Intel Corporation 100 Series/C230 Series Chipset Family SMBus [8086:a123] (rev 31)
   [INFO] Driver is 'i801_smbus' and will be rebound on VM exit
    [DRY] Not unbinding it
    [DRY] Not binding to vfio-pci

  Matched: 00:1f.6 Ethernet controller [0200]: Intel Corporation Ethernet Connection (2) I219-V [8086:15b8] (rev 31)
   [INFO] Driver is 'e1000e' and will be rebound on VM exit
    [DRY] Not unbinding it
    [DRY] Not binding to vfio-pci

  Matched: 01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GP106 [GeForce GTX 1060 6GB] [10de:1c03] (rev a1)
   [INFO] Driver is 'nvidia' and will be rebound on VM exit
    [DRY] Not unbinding it
    [DRY] Not binding to vfio-pci

  Matched: 01:00.1 Audio device [0403]: NVIDIA Corporation GP106 High Definition Audio Controller [10de:10f1] (rev a1)
   [INFO] Driver is 'snd_hda_intel' and will be rebound on VM exit
    [DRY] Not unbinding it
    [DRY] Not binding to vfio-pci

  Matched: 02:00.0 Non-Volatile memory controller [0108]: Samsung Electronics Co Ltd NVMe SSD Controller SM981/PM981/PM983 [144d:a808]
   [INFO] Driver is 'nvme' and will be rebound on VM exit
    [DRY] Not unbinding it
    [DRY] Not binding to vfio-pci

  Matched: 05:00.0 Network controller [0280]: Qualcomm Atheros QCA6174 802.11ac Wireless Network Adapter [168c:003e] (rev 32)
   [INFO] Driver is 'ath10k_pci' and will be rebound on VM exit
    [DRY] Not unbinding it
    [DRY] Not binding to vfio-pci

  Matched: 06:00.0 USB controller [0c03]: ASMedia Technology Inc. ASM1142 USB 3.1 Host Controller [1b21:1242]
   [INFO] Driver is 'xhci_hcd' and will be rebound on VM exit
    [DRY] Not unbinding it
    [DRY] Not binding to vfio-pci

---------------------
Here are the completed args from this DRY run:
Core: -machine q35,accel=kvm,kernel_irqchip=on -enable-kvm -m 8199624K -cpu host,kvm=off -smp sockets=1,cores=4,threads=1 -drive file=/var/lib/libvirt/images/Win10-Gaming.img,format=qcow2,id=disk -bios /usr/share/ovmf/x64/OVMF_CODE.fd
Net : -device virtio-net,netdev=network0 -netdev user,id=network0
USB : 
PCI :  -device vfio-pci,host=0000:00:00.0,id=hostdev0 -device vfio-pci,host=0000:00:01.0,id=hostdev1 -device vfio-pci,host=0000:00:14.0,id=hostdev2 -device vfio-pci,host=0000:00:16.0,id=hostdev3 -device vfio-pci,host=0000:00:17.0,id=hostdev4 -device vfio-pci,host=0000:00:1b.0,id=hostdev5 -device vfio-pci,host=0000:00:1c.0,id=hostdev6 -device vfio-pci,host=0000:00:1d.0,id=hostdev7 -device vfio-pci,host=0000:00:1d.1,id=hostdev8 -device vfio-pci,host=0000:00:1d.2,id=hostdev9 -device vfio-pci,host=0000:00:1f.0,id=hostdev10 -device vfio-pci,host=0000:00:1f.2,id=hostdev11 -device vfio-pci,host=0000:00:1f.3,id=hostdev12 -device vfio-pci,host=0000:00:1f.4,id=hostdev13 -device vfio-pci,host=0000:00:1f.6,id=hostdev14 -device vfio-pci,host=0000:01:00.0,id=hostdev15 -device vfio-pci,host=0000:01:00.1,id=hostdev16 -device vfio-pci,host=0000:02:00.0,id=hostdev17 -device vfio-pci,host=0000:05:00.0,id=hostdev18 -device vfio-pci,host=0000:06:00.0,id=hostdev19
Bios: 

Run the same command again but with '-run' to actually pass these to qemu-system-x86_64
```
As you can see I have specified it to only bind nvidia and the 3 specific devices. Any reason for this?

**Comment by ipaqmaster** [comment]
I was able to reproduce this on my machine when I included  `-pci '|'`

It's definitely that leading `|` pipe at the start of your `-pci` arguments however I'm not sure I expected that outcome anyway.

I'll try to fix that behavior for future but for now just remove the leading pipe in your arguments.

**Comment by TheGreatestJannet** [comment]
Thank you this works! When running the script the screen goes black with a static line and nothing happens although this is probably an issue with my configuration and not the script. Thank you for your help.

**Comment by ipaqmaster** [comment]
I just committed commit fc8c8c76ff970f57be9a7f057903413fe3a16af8 which will handle any leading/trailing `|` pipe  characters found in the regex before running their checks in future.

That's a bummer about your blank/terminal cursor blinking issue. If it becomes a pain feel free to make another issue thread down the line.

Sometimes I like to run it with 'nohup' prefixed to save the log for reading later which might help you debug any issue. Though I'd love to add its own logging feature down the line to make debugging easier and native.

**Comment by TheGreatestJannet** [comment]
I think the issue is I installed it as bios not UEFI.

**Comment by ipaqmaster** [comment]
Ah, that would be an issue. Though you mentioned you could pass your USB controller before though right? I thought it requires UEFI to do any PCI passthrough in the first place.

Unless this is a fresh install?

**Comment by TheGreatestJannet** [comment]
I’ve passed through usb fine with BIOS but I think GPUs need UEFI according to what I’ve read. https://blog.linuxserver.io/2017/04/28/how-to-setup-vfio-gpu-passthrough-using-ovmf-and-kvm-on-arch-linux/ Here it says it needs UEFI to reset the GPU without restarting the host machine.

**Comment by ipaqmaster** [comment]
I see, yes you might need to re-create it as an EFI machine then (Or convert it using the cmd)

Just quickly confirmed by making a new arch VM with an arch.iso and intentionally picking BIOS instead of EFI.

I successfully passed through the USB Controller on the back of my PC and as a result the VM took my keyboard and had full input from my keyboard even after I took away window focus, so it does seem that more basic PCI passthrough is supported by BIOS. I honestly thought you had to use EFI all the way, how about that.

But if your host is BIOS based you'll either need to re-create it using OVMF or upgrade it from BIOS>EFI with some sort of Microsoft-supported upgrade process. There are some guides out there for `mbr2gpt /convert` which claims to convert Win10 installs to EFI which is nice... but I would take a full backup of the guest image file first.

**Comment by TheGreatestJannet** [comment]
Having setup a EFI windows installation the issue still persists. I heard about Nvidia blocking pass through on 10 series cards and I have GTX 1060 6GB. Do you think this is the issue?

**Comment by ipaqmaster** [comment]
Sorry about the delay, had to sleep.

Unfortunately I've never owned a GTX 1XXX so I won't be able to comment. But my GTX 2080Ti started working after I installed the Nvidia driver in the guest to pick it up.

**Comment by TheGreatestJannet** [comment]
That’s fine. I’ll try installing the drivers. Also what desktop environment are you using? I read reports of gdm not killing all user sessions as mentioned here: https://github.com/joeknock90/Single-GPU-Passthrough. Also did you dump the bios of your GPU to get it working?

**Comment by ipaqmaster** [comment]
I have read that some models need a bios dump to make them work in VFIO situations however I haven't needed to do it for my run just yet.

I use lightdm as the display manager and cinnamon as the window manager but the script only deals with the service `display-manager` which registers as lightdm automatically. I expect it to dynamically change for anyone using a different one such as gdm, but not killing all user sessions could be problematic. I might test with it soon.

**Comment by TheGreatestJannet** [comment]
I’m using gnome 3 and GDM. The service display manager does stop GDM but I wonder if it’s not ending all user sessions causing the issue.

**Comment by TheGreatestJannet** [comment]
Also does the script use the virtual machine XML file? I’m unable to install the Nvidia drivers as the Nvidia GPU isn’t connected to the VM.

**Comment by TheGreatestJannet** [comment]
Running the script seems to get stuck at 100% CPU and no way to end the task the htop. The VM doesn’t start. The command I ran was: `sudo ./main -image /var/lib/libvirt/images/win10-Gaming.qcow2,format=qcow2 -bios '/usr/share/edk2-ovmf/x64/OVMF_CODE.fd' -pci 'NVIDIA'  -run`

**Comment by TheGreatestJannet** [comment]
Running the command with ssh shows that it gets stuck at unbinding Nvidia driver.

**Comment by ipaqmaster** [comment]
Its possible there's a bug. Could you reference that problem in a new issue?

**Comment by ipaqmaster** [comment]
Actually.. I just found a very bad typo which may be related to your issue. I've just pushed that, please pull the latest and see if it helps.

**Comment by TheGreatestJannet** [comment]
Sorry for the delay. I ha e tried the commit and the issue still occurs. I can open another issue if you want.

**Comment by TheGreatestJannet** [comment]
Hi I have figured it out. It seems that if you have nvidia-drm.modeset=1 as a kernel parameter it won’t be able to unbind the kernel driver. Removing it fixes the issue although I’m stuck at a black screen and need to figure out how to install the drivers!

**Comment by TheGreatestJannet** [comment]
Finally is there a way to use the xml libvirt settings with the script? I have setup the vm to use virtio as well as additional network interfaces and I don’t think they have applied.

**Comment by ipaqmaster** [comment]
Unfortunately this script doesn't have any libvirt config support. Once it generates the arguments it executes qemu-system-x86_64 directly on its own.

I was able to install the nvidia drivers myself however it could be another thing that needs to be supported on a case to case basis. I'll try using some other machines I have laying around to get a definite answer for you

**Comment by TheGreatestJannet** [comment]
Hello I got it working! I needed to dump my vbios for it to not get stuck on a black screen. I also opted for a libvirt script instead but I would like to thank you immensely for your help. I learnt I lot in the process (first time doing GPU passthrough) and your script taught me a lot. Thank you very much!

**Comment by TheGreatestJannet** [comment]
To fix the Nvidia drivers unbinding issue you need to unbind them in the following order: 
modprobe -r nvidia_drm
modprobe -r nvidia_modeset
modprobe -r nvidia_uvm
modprobe -r nvidia

Hope this helps!

**Comment by ipaqmaster** [comment]
Hey I'm glad you were able to get it going but you've also given me some ideas for the script's compatibility too which has been nice to work through. I'd love to make vbios dumping support automated for better support. Thanks for your time on this :)

I remember having to modprobe -r in that order in my original version of this script too (not public) however settled for unbinding the graphics card from the drivers, then binding it back once the VM exits (The modules are never unloaded) which should help segway me into multi-gpu support. We'll see though.
